### ISSUE TITLE
Testing stuff included in a pod for it

### ISSUE THREAD

**Issue by richardagist** [Tyler-Keith-Thompson/Workflow#1]
**Is your feature request related to a problem? Please describe.**
Testing things

**Describe the solution you'd like**
Include those testing mocks and listeners and asserters in a pod I can pull in on my test target

**Describe alternatives you've considered**
Copying everything from you and stealing it....

**Additional context**
God, Tyler.  We've already talked about this.

**Comment by Tyler-Keith-Thompson** [comment]
The subspec XCTest is available 

```ruby
pod install DynamicWorkflow/XCTest
```

For consumption now. It includes a WorkflowListener, a MockPresenter and just for kicks it solves the problem where the file and line weren't being reported at the place they actually failed.
