### ISSUE TITLE
staysInViewStack .hiddenInitially is not setting the proceedInWorkflow when coming back to the screen

### ISSUE THREAD

**Issue by richardagist** [Tyler-Keith-Thompson/Workflow#3]
**Describe the bug**
Setting a .thenPresent to have a hiddenInitially seems to forget to set the proceedInWorkflow when you navigate back the view.

**To Reproduce**
1. Setup a workflow with hiddenInitially
2. Skip the hiddenInitially
3. Navigate back to the hiddenInitially
4. Try to proceed foorward

**Expected behavior**
Be able to move forward.

**Additional context**
 - XCode Version: 11.3.1
 - Workflow Version: 1.0.5

Sample:
See comments

**Comment by richardagist** [comment]
Put this code on a viewController in a sample app
`
    override func viewDidAppear(_ animated: Bool) {
        class Skippy: UIWorkflowItem<Never>, FlowRepresentable {
            static func instance() -> AnyFlowRepresentable { Skippy() }
            func shouldLoad() -> Bool { false }
            override func viewDidLoad() { title = "Skip" }
            override func viewWillAppear(_ animated: Bool) {
                proceedInWorkflow()
            }
        }

        class StayPuty: UIWorkflowItem<Never>, FlowRepresentable {
            static func instance() -> AnyFlowRepresentable { StayPuty() }
            func shouldLoad() -> Bool { true }
            override func viewDidLoad() { title = "Stay Put" }
        }
        
        let problemWorkflow = Workflow()
            .thenPresent(Skippy.self, presentationType: .default, staysInViewStack: .hiddenInitially)
            .thenPresent(StayPuty.self)
        launchInto(problemWorkflow, withLaunchStyle: .navigationStack)
    }
`

**Comment by Tyler-Keith-Thompson** [comment]
```Swift
  var itWorky = true
```

Should be fixed in 1.0.6, thanks for catching this!
