### ISSUE TITLE
Clear view stack when calling abandon on workflow that created the rootViewController

### ISSUE THREAD

**Issue by richardagist** [Tyler-Keith-Thompson/Workflow#4]
**Is your feature request related to a problem? Please describe.**
I have a custom `UITabBarController` that has a custom `UINavigationController` which I then use to launch into a predefined workflow.  Under certain circumstances I want to relaunch the workflow with a new argument being passed in.
I would like `abandon` to clear the rootViewController from my custom navigation controller so that I have a clean slate for relaunching my workflow.

**Describe the solution you'd like**
I would like to be able to simply call
`workflow.abandon(); viewcontroller?.launchInto(workflow, args: argy)`
And when this is called, no matter how many times, I would only see the viewControllers defined in the workflow, and not any lingering view controllers.

**Describe alternatives you've considered**
`(viewController as? UINavigationController)?.viewControllers = []`

**Additional context**
Reach out if you need more sample code.

**Comment by Tyler-Keith-Thompson** [comment]
1.0.11 *should* solve your problem.
