### ISSUE TITLE
Finish up Github documentation

### ISSUE THREAD

**Issue by Richard-Gist** [Tyler-Keith-Thompson/Workflow#7]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like
A completed CONTRIBUTE.md and working templates.

### Describe alternatives you've considered
None

### Additional context
We've discussed that things are not complete.  This issue is to help test the process.

**Comment by Tyler-Keith-Thompson** [comment]
Hey Richard thanks for reaching out, the latest version of Workflow has the changes you wanted in it. Please let us know if you have any issues.
